# To build image run `docker build -f Dockerfile.jvm --tag ddns-jvm:<version> .`

ARG OPENJDK_VERSION=25
ARG OPENJDK_WORKDIR=/openjdk/src/project

# Multi-stage image ... creates intermediate layer(s) for doing the build
FROM eclipse-temurin:${OPENJDK_VERSION}-jdk-alpine AS build

ARG GRADLE_VERSION=9.3.1
ARG OPENJDK_WORKDIR=/openjdk/src/project

# Install tools required for project
RUN apk update \
 && apk add wget unzip \
 && wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -P /tmp \
 && unzip -d /opt /tmp/gradle-${GRADLE_VERSION}-bin.zip

ENV GRADLE_HOME=/opt/gradle-${GRADLE_VERSION}
ENV PATH=${GRADLE_HOME}/bin:${PATH}

WORKDIR ${OPENJDK_WORKDIR}

# Copy the entire project and build it
COPY . ${OPENJDK_WORKDIR}
RUN ${GRADLE_HOME}/bin/gradle -q --no-daemon shadowJar

# Runtime image
FROM eclipse-temurin:${OPENJDK_VERSION}-jre-alpine AS ddns-base

ARG OPENJDK_WORKDIR=/openjdk/src/project

ENV DDNS_HOME=/opt/ddns
ENV PATH=${DDNS_HOME}/bin:${PATH}

WORKDIR ${DDNS_HOME}

COPY --from=build ${OPENJDK_WORKDIR}/ddns* ${OPENJDK_WORKDIR}/build/libs/* ${DDNS_HOME}/

FROM ddns-base AS ddns
ENTRYPOINT [ "java" ]
CMD [ "-jar" , "ddns.jar" , "-d" ]
